### ISSUE TITLE
Failure to find javax.persistence:persistence-api:jar:2.1 

### ISSUE THREAD

**Issue by gravin** [dayatang/hrm-demo#2]
Failure to find javax.persistence:persistence-api:jar:2.1 

应该是1.0.2 ,搞的项目怎么出错连连啊

**Comment by dayatang** [comment]
使用http://nexus.dddlib.org/content/groups/public-releases/仓库地址。该仓库中存在这个 javax.persistence:persistence-api:jar:2.1。
